

/**
 * Compendium (NLP knowledge base)
 */

(function() {
    extend(cpd, {

        // Regular verbs
        // Conjugated and expanded in compendium.parser.js
        verbs: ['accept',
                'add',
                'admire',
                'admit',
                'advise',
                'afford',
                'agree',
                'alert',
                'allow',
                'amuse',
                'analyse',
                'analyze',
                'announce',
                'annoy',
                'answer',
                'apologise',
                'appear',
                'applaud',
                'appreciate',
                'approve',
                'argue',
                'arrange',
                'arrest',
                'arrive',
                'ask',
                'attach',
                'attack',
                'attempt',
                'attend',
                'attract',
                'avoid',
                'back',
                'bake',
                'balance',
                'ban',
                'bang',
                'bare',
                'bat',
                'bathe',
                'battle',
                'beam',
                'beg',
                'behave',
                'belong',
                'bleach',
                'bless',
                'blind',
                'blink',
                'blot',
                'blush',
                'boast',
                'boil',
                'bolt',
                'bomb',
                'book',
                'bore',
                'borrow',
                'bounce',
                'bow',
                'box',
                'brake',
                'branch',
                'breathe',
                'bruise',
                'brush',
                'bubble',
                'bump',
                'burn',
                'bury',
                'buzz',
                'calculate',
                'call',
                'camp',
                'care',
                'carry',
                'carve',
                'cause',
                'challenge',
                'change',
                'charge',
                'chase',
                'cheat',
                'check',
                'cheer',
                'chew',
                'choke',
                'chop',
                'claim',
                'clap',
                'clean',
                'clear',
                'clip',
                'close',
                'coach',
                'coil',
                'collect',
                'colour',
                'comb',
                'command',
                'communicate',
                'compare',
                'compete',
                'complain',
                'complete',
                'concentrate',
                'concern',
                'confess',
                'confuse',
                'connect',
                'consider',
                'consist',
                'contain',
                'continue',
                'copy',
                'correct',
                'cough',
                'count',
                'cover',
                'crack',
                'crash',
                'crawl',
                'cross',
                'crush',
                'cry',
                'cure',
                'curl',
                'curve',
                'cycle',
                'dam',
                'damage',
                'dance',
                'dare',
                'decay',
                'deceive',
                'decide',
                'decorate',
                'delay',
                'delight',
                'deliver',
                'depend',
                'describe',
                'desert',
                'deserve',
                'destroy',
                'detect',
                'develop',
                'disagree',
                'disappear',
                'disapprove',
                'disarm',
                'discover',
                'dislike',
                'divide',
                'double',
                'doubt',
                'drag',
                'drain',
                'dream',
                'dress',
                'drip',
                'drop',
                'drown',
                'drum',
                'dry',
                'dust',
                'earn',
                'educate',
                'embarrass',
                'employ',
                'empty',
                'encourage',
                'end',
                'enjoy',
                'enter',
                'entertain',
                'escape',
                'examine',
                'excite',
                'excuse',
                'exercise',
                'exist',
                'expand',
                'expect',
                'explain',
                'explode',
                'extend',
                'face',
                'fade',
                'fail',
                'fancy',
                'fasten',
                'fax',
                'fear',
                'fence',
                'fetch',
                'file',
                'fill',
                'film',
                'fire',
                'fit',
                'fix',
                'flap',
                'flash',
                'float',
                'flood',
                'flow',
                'flower',
                'fold',
                'follow',
                'fool',
                'force',
                'form',
                'found',
                'frame',
                'frighten',
                'fry',
                'gather',
                'gaze',
                'glow',
                'glue',
                'grab',
                'grate',
                'grease',
                'greet',
                'grin',
                'grip',
                'groan',
                'guarantee',
                'guard',
                'guess',
                'guide',
                'hammer',
                'hand',
                'handle',
                'hang',
                'happen',
                'harass',
                'harm',
                'hate',
                'haunt',
                'head',
                'heal',
                'heap',
                'heat',
                'help',
                'hook',
                'hop',
                'hope',
                'hover',
                'hug',
                'hum',
                'hunt',
                'hurry',
                'identify',
                'ignore',
                'imagine',
                'impress',
                'improve',
                'include',
                'increase',
                'influence',
                'inform',
                'inject',
                'injure',
                'instruct',
                'intend',
                'interest',
                'interfere',
                'interrupt',
                'introduce',
                'invent',
                'invite',
                'irritate',
                'itch',
                'jail',
                'jam',
                'jog',
                'join',
                'joke',
                'judge',
                'juggle',
                'jump',
                'kick',
                'kill',
                'kiss',
                'kneel',
                'knit',
                'knock',
                'knot',
                'label',
                'land',
                'last',
                'laugh',
                'launch',
                'learn',
                'level',
                'license',
                'lick',
                'lie',
                'lighten',
                'like',
                'list',
                'listen',
                'live',
                'load',
                'lock',
                'long',
                'look',
                'love',
                'man',
                'manage',
                'march',
                'mark',
                'marry',
                'match',
                'mate',
                'matter',
                'measure',
                'meddle',
                'melt',
                'memorise',
                'mend',
                'mess',
                'up',
                'milk',
                'mine',
                'miss',
                'mix',
                'moan',
                'moor',
                'mourn',
                'move',
                'muddle',
                'mug',
                'multiply',
                'murder',
                'nail',
                'name',
                'need',
                'nest',
                'nod',
                'note',
                'notice',
                'number',
                'obey',
                'object',
                'observe',
                'obtain',
                'occur',
                'offend',
                'offer',
                'open',
                'order',
                'overflow',
                'owe',
                'own',
                'pack',
                'paddle',
                'paint',
                'park',
                'part',
                'pass',
                'paste',
                'pat',
                'pause',
                'peck',
                'pedal',
                'peel',
                'peep',
                'perform',
                'permit',
                'phone',
                'pick',
                'pinch',
                'pine',
                'place',
                'plan',
                'plant',
                'play',
                'please',
                'plug',
                'point',
                'poke',
                'polish',
                'pop',
                'possess',
                'post',
                'pour',
                'practise',
                'practice',
                'pray',
                'preach',
                'precede',
                'prefer',
                'prepare',
                'present',
                'preserve',
                'press',
                'pretend',
                'prevent',
                'prick',
                'print',
                'produce',
                'program',
                'promise',
                'protect',
                'provide',
                'pull',
                'pump',
                'punch',
                'puncture',
                'punish',
                'push',
                'question',
                'queue',        
                'race',
                'radiate',
                'rain',
                'raise',
                'reach',
                'realise',
                'receive',
                'recognise',
                'record',
                'reduce',
                'reflect',
                'refuse',
                'regret',
                'reign',
                'reject',
                'rejoice',
                'relax',
                'release',
                'rely',
                'remain',
                'remember',
                'remind',
                'remove',
                'repair',
                'repeat',
                'replace',
                'reply',
                'report',
                'reproduce',
                'request',
                'rescue',
                'retire',
                'return',
                'rhyme',
                'rinse',
                'risk',
                'rob',
                'rock',
                'roll',
                'rot',
                'rub',
                'ruin',
                'rule',
                'rush',
                'sack',
                'sail',
                'satisfy',
                'save',
                'saw',
                'scare',
                'scatter',
                'scold',
                'scorch',
                'scrape',
                'scratch',
                'scream',
                'screw',
                'scribble',
                'scrub',
                'seal',
                'search',
                'separate',
                'serve',
                'settle',
                'shade',
                'share',
                'shave',
                'shelter',
                'shiver',
                'shock',
                'shop',
                'shrug',
                'sigh',
                'sign',
                'signal',
                'sin',
                'sip',
                'ski',
                'skip',
                'slap',
                'slip',
                'slow',
                'smash',
                'smell',
                'smile',
                'smoke',
                'snatch',
                'sneeze',
                'sniff',
                'snore',
                'snow',
                'soak',
                'soothe',
                'sound',
                'spare',
                'spark',
                'sparkle',
                'spell',
                'spill',
                'spoil',
                'spot',
                'spray',
                'sprout',
                'squash',
                'squeak',
                'squeal',
                'squeeze',
                'stain',
                'stamp',
                'stare',
                'start',
                'stay',
                'steer',
                'step',
                'stir',
                'stitch',
                'stop',
                'store',
                'strap',
                'strengthen',
                'stretch',
                'strip',
                'stroke',
                'stuff',
                'subtract',
                'succeed',
                'suck',
                'suffer',
                'suggest',
                'suit',
                'supply',
                'support',
                'suppose',
                'surprise',
                'surround',
                'suspect',
                'suspend',
                'switch',
                'talk',
                'tame',
                'tap',
                'taste',
                'tease',
                'telephone',
                'tempt',
                'terrify',
                'test',
                'thank',
                'thaw',
                'tick',
                'tickle',
                'tie',
                'time',
                'tip',
                'tire',
                'touch',
                'tour',
                'tow',
                'trace',
                'trade',
                'train',
                'transport',
                'trap',
                'travel',
                'treat',
                'tremble',
                'trick',
                'trip',
                'trot',
                'trouble',
                'trust',
                'try',
                'tug',
                'tumble',
                'turn',
                'twist',
                'type',
                'undress',
                'unfasten',
                'unite',
                'unlock',
                'unpack',
                'untidy',
                'use',
                'vanish',
                'visit',        
                'wail',
                'wait',
                'walk',
                'wander',
                'want',
                'warm',
                'warn',
                'wash',
                'waste',
                'watch',
                'water',
                'wave',
                'weigh',
                'welcome',
                'whine',
                'whip',
                'whirl',
                'whisper',
                'whistle',
                'wink',
                'wipe',
                'wish',
                'wobble',
                'wonder',
                'work',
                'worry',
                'wrap',
                'wreck',
                'wrestle',
                'wriggle',       
                'yawn',
                'yell',         
                'zip',
                'zoom'
        ],

        // Common exceptions to the words ending with "ing"
        // but that are not the gerund of a verb
        ing_excpt: [
            'anything',
            'spring',
            'something',
            'thing',
            'king',
            'nothing'
        ],

        // Adverbs 
        emphasis: [
            'totally',
            'fully',
            'really',
            'surprisingly',
            'absolutely',
            'actively',
            'clearly',
            'crazily',
            'greatly',
            'happily',
            'notably',
            'severly',
            'particularly',
            'highly',
            'quite',
            'pretty',
            'seriously'
        ],

        // Thanks to https://github.com/spencermountain/nlp_compromise
        // for initial list.
        // Odd entries are abbreviations, even entries are replacement
        // potentially ambiguous abbrvs have no replacement.
        // Replacements are extracted from this array and 
        // added in `abbrs_rplt` when lexicon is parsed (see lexicon.js).
        abbrs: [
            // millenials
            'srsly', 'seriously',
            'nah', 'no',
            //honourifics
            'jr', 'junior',
            'mr', 'mister',
            'mrs', 'missus',
            'ms', 'miss',
            'dr', 'doctor',
            'prof', 'professor',
            'pr', 'professor',
            'sr', 'senior',
            'sen', 'senator',
            'sens', 'senators',
            'corp', 'corporation',
            'rep', '',
            'gov', '',
            'atty', 'attorney',
            'supt', 'superintendent',
            'det', 'detective',
            'rev', '',
            'col', 'colonel',
            'gen', 'general',
            'lt', 'lieutenant',
            'cmdr', 'commander',
            'adm', 'administrative',
            'capt', 'captain',
            'sgt', 'sergent',
            'cpl', 'caporal',
            'maj', '',
            'esq', 'esquire',
            'phd', '',
            'adj', 'adjective',
            'adv', 'adverb',
            'asst', 'assistant',
            'bldg', 'building',
            'brig', 'brigade',
            'hon', '',
            'messrs', 'messeurs',
            'mlle', 'mademoiselle',
            'mme', 'madame',
            'op', '',
            'ord', 'order',
            'pvt', 'private',
            'reps', '',
            'res', '',
            'sens', '',
            'sfc', '',
            'surg', 'surgeon',
            'ph', '',
            'ds', '',
            //common abbreviations
            'arc', '',
            'al', '',
            'ave', 'avenue',
            'blvd', 'boulevard',
            'cl', '',
            'ct', '',
            'cres', '',
            'exp', '',
            'rd', 'road',
            'st', 'street',
            'dist', '',
            'mt', 'mount',
            'ft', '',
            'fy', '',
            'hwy', 'highway',
            'la', '',
            'pd', '',
            'pl', '',
            'plz', '',
            'tce', '',
            'vs', '',
            'etc', '',
            'esp', '',
            'llb', '',
            'md', '',
            'bl', '',
            'ma', '',
            'ba', '',
            'lit', '',
            'fl', '',
            'ex', 'example',
            'eg', '',
            //place abbrevs
            'ala', 'alabama',
            'ariz', 'arizona',
            'ark', 'arkansas',
            'cal', 'california',
            'calif', 'california',
            'col', 'coloradoa',
            'colo', 'colorado',
            'conn', 'connecticut',
            'del', 'delaware',
            'fed', 'federal',
            'fla', 'florida',
            'ga', 'georgia',
            'ida', 'idaho',
            'id', 'idaho',
            'ill', 'illinois',
            'ind', 'indiana',
            'ia', 'iowa', 
            'kan', 'kansas',
            'kans', 'kansas',
            'ken', 'kentuky',
            'ky', 'kentuky',
            'la', '',
            'me', '',
            'md', '',
            'mass', 'massachussets',
            'mich', 'michigan',
            'minn', 'minnesota',
            'miss', 'mississippi',
            'mo', 'missouri',
            'mont', 'montana',
            'neb', 'nebraska',
            'nebr', 'nebraska',
            'nev', 'nevada',
            'mex', 'mexico',
            'okla', 'oklahoma',
            'ok', 'oklahoma',
            'ore', 'oregon',
            'penna', 'pennsylvania',
            'penn', 'pennsylvania',
            'pa', 'pennsylvania',
            'dak', 'dakota',
            'tenn', 'tennessee',
            'tex', 'texas',
            'ut', 'utah',
            'vt', 'vermont',
            'va', 'virginia',
            'wash', 'washington',
            'wis', 'wisconsin',
            'wisc', 'wisconsin',
            'wy', 'wyoming',
            'wyo', 'wyoming',
            'alta', 'alberta',
            'ont', 'ontario',
            'que', 'quebec',
            'sask', 'saskatchewan',
            'yuk', 'yukon',
            //date abbrevs
            'jan', 'january',
            'feb', 'february',
            'mar', 'march',
            'apr', 'april',
            'jun', 'june',
            'jul', 'july',
            'aug', 'august',
            'sep', 'september',
            'oct', 'october',
            'nov', 'november',
            'dec', 'december',
            'sept', 'september',
            //org abbrevs
            'dept', 'department',
            'univ', 'university',
            'assn', 'association',
            'bros', 'brothers',
            'inc', 'incorported',
            'ltd', 'limited',
            'co', ''
        ],

        synonyms: '@@synonyms',

        // Abbreviation replacements
        // (populated by parser)
        abbrs_rplt: [],

        //proper nouns with exclamation marks
        exclamations: [
            'yahoo', 
            'joomla', 
            'jeopardy'
        ],

        // Rules from `rules.txt`, 
        // populated by gulpfile and parsed by compendium.parser.js
        rules: '@@rules',

        // Suffixes from `suffixes.txt`
        // populated by gulpfile and parsed by compendium.parser.js
        suffixes: '@@suffixes',

        // Raw emoticons, populated by compendium.parser.js
        emots: [],

        // Numbers and their value
        // (PoS tag `CD`)
        numbers: {
            zero: 0,
            one: 1,
            two: 2,
            three: 3,
            four: 4,
            five: 5,
            six: 6,
            seven: 7,
            eight: 8,
            nine: 9,
            ten: 10,
            eleven: 11,
            twelve: 12,
            thirteen: 13,
            fourteen: 14,
            fifteen: 15,
            sixteen: 16,
            seventeen: 17,
            eighteen: 18,
            nineteen: 19,
            ninteen: 19,
            twenty: 20,
            thirty: 30,
            forty: 40,
            fourty: 40,
            fifty: 50,
            sixty: 60,
            seventy: 70,
            eighty: 80,
            ninety: 90,
            hundred: 100,
            thousand: 1000,
            million: 1000000,
            billion: 1000000000,
            trillion: 1000000000000
        },

        nationalities: {
            afghan: 'JJ',
            albanian: 'JJ',
            algerian: 'JJ',
            argentine: 'JJ',
            armenian: 'JJ',
            australian: 'JJ',
            aussie: 'JJ',
            austrian: 'JJ',
            bangladeshi: 'JJ',
            belgian: 'JJ',
            bolivian: 'JJ',
            bosnian: 'JJ',
            brazilian: 'JJ',
            bulgarian: 'JJ',
            cambodian: 'JJ',
            canadian: 'JJ',
            chilean: 'JJ',
            chinese: 'JJ',
            colombian: 'JJ',
            croat: 'JJ',
            cuban: 'JJ',
            czech: 'JJ',
            dominican: 'JJ',
            egyptian: 'JJ',
            british: 'JJ',
            estonian: 'JJ',
            ethiopian: 'JJ',
            finnish: 'JJ',
            french: 'JJ',
            gambian: 'JJ',
            georgian: 'JJ',
            german: 'JJ',
            greek: 'JJ',
            haitian: 'JJ',
            hungarian: 'JJ',
            indian: 'JJ',
            indonesian: 'JJ',
            iranian: 'JJ',
            iraqi: 'JJ',
            irish: 'JJ',
            israeli: 'JJ',
            italian: 'JJ',
            jamaican: 'JJ',
            japanese: 'JJ',
            jordanian: 'JJ',
            kenyan: 'JJ',
            korean: 'JJ',
            kuwaiti: 'JJ',
            latvian: 'JJ',
            lebanese: 'JJ',
            liberian: 'JJ',
            libyan: 'JJ',
            lithuanian: 'JJ',
            macedonian: 'JJ',
            malaysian: 'JJ',
            mexican: 'JJ',
            mongolian: 'JJ',
            moroccan: 'JJ',
            dutch: 'JJ',
            nicaraguan: 'JJ',
            nigerian: 'JJ',
            norwegian: 'JJ',
            omani: 'JJ',
            pakistani: 'JJ',
            palestinian: 'JJ',
            filipino: 'JJ',
            polish: 'JJ',
            portuguese: 'JJ',
            qatari: 'JJ',
            romanian: 'JJ',
            russian: 'JJ',
            rwandan: 'JJ',
            samoan: 'JJ',
            saudi: 'JJ',
            scottish: 'JJ',
            senegalese: 'JJ',
            serbian: 'JJ',
            singaporean: 'JJ',
            slovak: 'JJ',
            somali: 'JJ',
            sudanese: 'JJ',
            swedish: 'JJ',
            swiss: 'JJ',
            syrian: 'JJ',
            taiwanese: 'JJ',
            thai: 'JJ',
            tunisian: 'JJ',
            ugandan: 'JJ',
            ukrainian: 'JJ',
            american: 'JJ',
            hindi: 'JJ',
            spanish: 'JJ',
            venezuelan: 'JJ',
            vietnamese: 'JJ',
            welsh: 'JJ',
            african: 'JJ',
            european: 'JJ',
            asian: 'JJ',
            californian: 'JJ'
        },

        // Negation marks
        neg: {
            not: 'RB',
            'n\'t':  'RB',
            '\'t':  'RB',
            no: 'RB',
            neither: 'DT',
            nor: 'DT',
            never: 'RB',
            without: 'IN',
            except: 'IN',
            absent: 'JJ',
            unlike: 'IN',
            unable: 'JJ',
            unremarkable: 'JJ',
            unlikely: 'JJ',
            negative: 'JJ',
            hardly: 'RB',
            deny: 'VB',
            fail: 'VB',
            exclude: 'VB',
            lack: 'NN',
            absence: 'NN',
            none: 'NN'
        },

        // Counter negation marks
        neg_neg: {
            only: 'RB',
            just: 'RB',
            solely: 'RB',
            uniquely: 'RB',
            exclusively: 'RB'
        },

        // Breakpoints words
        breakpoints: {
            
        },

        // Personal pronouns
        // filtered in lexicon (y?)
        p: {
            i: 'PRP',
            you: 'PRP'
        },

        // For date recognition
        months: {
            january: 'NNP',
            february: 'NNP',
            march: 'NNP',
            april: 'NNP',
            may: 'NNP',
            june: 'NNP',
            july: 'NNP',
            august: 'NNP',
            september: 'NNP',
            october: 'NNP',
            november: 'NNP',
            december: 'NNP'
        },
        days: {
            monday: 'NNP',
            tuesday: 'NNP',
            wednesday: 'NNP',
            thursday: 'NNP',
            friday: 'NNP',
            saturday: 'NNP',
            sunday: 'NNP'
        },

        indicators: {
            first: 'JJ',
            both: 'DT',
            second: 'JJ',
            third: 'JJ',
            last: 'JJ',
            previous: 'JJ',
            next: 'JJ',
            latest: 'JJ',
            earliest: 'JJ'
        },

        // Profiling
        dirty: [
            'anal','anus','arse','ass','asshole','ballsack','bastard','bitch',
            'biatch','bloody','blowjob','blow job','bollock','bollok',
            'boner','boob','bugger','bum','butt','buttplug','clitoris','cock',
            'coon','crap','cunt','damn','dick','dildo','dyke','fag',
            'feck','fellate','fellatio','felching','fuck','fucking','fudgepacker','fudge packer','flange',
            'homo','jerk','jizz','knobend','knob end','labia','lmfao','muff',
            'nigger','nigga','penis','piss','poop','prick','pube',
            'pussy','queer','scrotum','sex','shit','s hit','sh1t','slut','smegma',
            'spunk','tit','tosser','turd','twat','vagina','wank','whore', 'crappy'
        ],

        polite: ['thanks', 'thank', 'please', 'excuse', 'pardon', 'welcome', 'sorry', 'might']
    });
}());